### ISSUE TITLE
WooCommerce default pagination limit to 10 prevents import of all products or categories

### ISSUE THREAD

**Issue by albertolopezma** [OCA/connector-woocommerce#11]
Reviewing the connector I found some issues in the import logic of products and categories.

When importing products, no more than 10 results are included, this seems to be related to default pagination limit of 10 results per page in WooCommerce and default page=1 setting.

Using Python example code from WooCommerce module version 1.0.4, it is necessary to change the filter setting as in `products?filter[limit]=9999` to get more than 10 products in an API call:

``` python
from woocommerce import API

wcapi = API(
    url="http://example.com",
    consumer_key="ck_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    consumer_secret="cs_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    version="v2"
)

r = wcapi.get('products')

s = wcapi.get('products?filter[limit]=9999')

```

This seems to be the case for connector-woocommerce module. I think the connector uses the filter feature to filter by date, but leaves limit and pagination settings to their default values.

It may be necessary to use the filter limit parameter or, even better, to break down product and category import in batches of a fixed number of elements, i.e. 100 per run, running multiple times until every product and category is fetched.

**Comment by maricarlortiz** [comment]
Hi @albertolopezma how did you fix this? the issue is closed but I still encounter this situation on the recent version.
