### ISSUE TITLE
Export Products from Odoo

### ISSUE THREAD

**Issue by jimmymic** [OCA/connector-woocommerce#28]
Is it possible to export products from Odoo to Woo

We already have a vast array of products and stock setup in odoo.

If someone can point me in the right direction that would be appreciated.

The video demo only appears to be for syncing products and categories created in woo first.

**Comment by parthivgls** [comment]
@jimmymic at the moment, export from Odoo to Woo is not possible, What we have generally seen is people prefer to configure their product in Woo first, set description, SEO related data etc. and then bring only partial data like name, category, price to Odoo.
