### ISSUE TITLE
Rename `woocommerceerpconnect`?

### ISSUE THREAD

**Issue by dreispt** [OCA/connector-woocommerce#3]
Module name usually use underscores to replace spaces.
It sound to me that `woocommerce_connector` or `connector_woocommerce` would be more appropriate.

Opinions?

**Comment by pedrobaeza** [comment]
:+1:

**Comment by guewen** [comment]
The recommendation is connector_woocommerce http://odoo-connector.com/project/contribute.html#naming-conventions
