### ISSUE TITLE
how to install connector woocommerce

### ISSUE THREAD

**Issue by patrickpeng2091** [OCA/connector-woocommerce#38]
How to install connector woocommerce? I moved addons directory below,  upgrade and update, but do not display?

**Comment by rubencabrera** [comment]
I'm very sorry to say that this repo seems abandoned due to a private development that you can find on odoo apps. This doesn't mean that it's not worth an effort, but don't count on a lot of help for it.

**Comment by pedrobaeza** [comment]
Yeah, the module was contributed in 8.0, and improve in https://github.com/OCA/connector-woocommerce/pull/31, but nobody has attend more about it.
