### ISSUE TITLE
External ID not found in the system: base.menu_config"

### ISSUE THREAD

**Issue by elfarsaouiomar** [OCA/connector-woocommerce#45]
**Hello i'm new in odoo , downloaded the Odoo connector_woocommerce into apps folder, and changed all _manifest files to install true. Tried then installing but gives me this error:**

```
raise ValueError('External ID not found in the system: %s' % xmlid) ParseError:
"External ID not found in the system: base.menu_config" while parsing /home/hero/odoo-10.0/odoo/addons/connector/setting_view.xml:44, near
```

**i'm using ubuntu 18.04.1 , odoo v 10 .
Any idea how to fix?**

**Comment by pedrobaeza** [comment]
This is because the module is not migrated. That's why it puts installable=False.
